# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='favourite',
        ),
        migrations.AddField(
            model_name='quote',
            name='favourite',
            field=models.ManyToManyField(related_name='fav_list', to='first_app.User'),
        ),
    ]
